### ISSUE TITLE
$errors array is empty until $validate is manually called

### ISSUE THREAD

**Issue by sqal** [jrenton/vue-validity#2]
Like in the title. I have simple input. i have entered part of my name into the input field, but the $error array is empty and there should be one error -> minlength. It only shows after I run $validate method myself.

```
{
  "name": "Pa"
}
{
  "required": {
    "$value": true,
    "$message": "name is required."
  },
  "minlength": {
    "$value": false,
    "$message": "name should be at least 3 chars."
  },
  "$valid": false,
  "$dirty": false,
  "$error": false,
  "$errors": []
}
```

is this intended behavior?

**Comment by jrenton** [comment]
Hi @sqal. This was intended behavior but I can see the reason for accessing `$errors` anytime `$valid` is false. I think I will change this.

**Comment by jrenton** [comment]
@sqal Ok in `0.2.0` I have changed that functionality
